basePath: /
consumes:
    - application/json
definitions:
    ErrResponse:
        properties:
            code:
                format: int64
                type: integer
                x-go-name: Code
            message:
                type: string
                x-go-name: Message
        type: object
        x-go-package: x_go_swagger/api
    User:
        properties:
            age:
                description: 年龄
                format: int64
                type: integer
                x-go-name: Age
            like:
                description: 喜好
                type: string
                x-go-name: Like
            name:
                description: 名字
                type: string
                x-go-name: Name
            sex:
                description: 性别
                type: string
                x-go-name: Sex
        required:
            - name
        type: object
        x-go-package: x_go_swagger/api
host: 127.0.0.1:9501
info:
    description: Documentation of our awesome API.
    title: awesome .
    version: 0.1.0
paths:
    /user:
        get:
            description: 查找用户
            operationId: getUserRequest
            parameters:
                - description: in.path
                  in: query
                  name: name
                  required: true
                  type: string
                  x-go-name: Name
            responses:
                "200":
                    $ref: '#/responses/getUserResponse'
                default:
                    $ref: '#/responses/errResponse'
            tags:
                - user
produces:
    - application/json
responses:
    errResponse:
        description: ""
        headers:
            Body:
                description: in.body
        schema:
            $ref: '#/definitions/ErrResponse'
    getUserResponse:
        description: ""
        headers:
            Body:
                description: in.body
        schema:
            $ref: '#/definitions/User'
schemes:
    - http
    - https
securityDefinitions:
    basic:
        type: basic
swagger: "2.0"
