basePath: /
consumes:
    - application/json
host: 127.0.0.1:9501
info:
    description: Documentation of our awesome API.
    title: awesome .
    version: 0.1.0
paths: {}
produces:
    - application/json
schemes:
    - http
    - https
securityDefinitions:
    basic:
        type: basic
swagger: "2.0"
